In [1]:
import pandas as pd

from sklearn.metrics import roc_auc_score

# Data

In [2]:
df_nn = pd.read_csv('../data/nn_df.csv')
df_ml = pd.read_csv('../data/ml_df.csv')

In [3]:
df_nn

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,predicted_logits,fold_n,nn_pred
0,0.954814,1,3,0.753336,-0.278393,1,0,0.019590,0,1.083536,0,-0.707350,-2.134019,1,0.867925,4,0.704314
1,-1.914086,1,2,-0.098037,0.051329,0,1,1.638201,0,2.118574,0,-0.707350,-0.504704,1,1.572217,3,0.828099
2,-1.472716,0,1,-0.098037,-0.840861,0,0,0.982007,0,0.307259,2,-0.707350,-0.504704,1,2.117491,4,0.892592
3,0.182418,1,1,-0.665619,-0.220207,0,1,1.244485,0,-0.210260,2,-0.707350,-0.504704,1,1.819378,1,0.860491
4,0.292760,0,0,-0.665619,2.068456,0,1,0.588291,1,-0.382766,2,-0.707350,-0.504704,1,0.248983,2,0.561926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,0.954814,1,0,0.469545,-1.170584,0,0,-0.242887,1,2.549839,2,1.237862,1.124612,0,-3.144876,1,0.041294
293,0.954814,0,0,-0.438586,-0.976630,0,1,-0.592857,1,-0.900285,1,-0.707350,-0.504704,0,-0.872228,3,0.294791
294,0.513445,1,0,1.831741,-1.383934,1,0,-2.605185,0,-0.037754,1,1.237862,-2.134019,0,-0.852357,4,0.298939
295,0.292760,0,0,0.469545,-0.123230,0,1,-1.161559,1,-0.727779,1,-0.707350,1.124612,0,-0.819010,1,0.305974
296,-1.031347,1,3,-1.233201,0.322866,0,1,-0.767842,0,0.134752,1,-0.707350,1.124612,0,0.478889,4,0.617486

In [4]:
df_ml

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,svc_pred,rf_pred,logreg_pred,gbc_pred
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,0.841579,0.636878,0.772852,0.739894
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,0.838055,0.667742,0.760161,0.864369
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,0.901693,0.720617,0.956759,0.995242
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,0.797452,0.709785,0.894069,0.950563
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,0.790381,0.543625,0.830705,0.833448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0,0.041840,0.324801,0.006403,0.008247
293,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0,0.773440,0.510220,0.813761,0.830272
294,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0,0.055762,0.432082,0.015432,0.013110
295,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0,0.365503,0.446688,0.398556,0.717099
296,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0,0.793551,0.568825,0.729744,0.557509

# Blend

In [5]:
target = df_nn['target']

In [31]:
roc_auc_score(
    target,
    (df_ml['rf_pred'] + df_nn['nn_pred'] + df_ml['logreg_pred']*0.75 + df_ml['gbc_pred']*0.05) 
)

0.9188385916780978